name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl autoconf bison build-essential libssl-dev \
            libyaml-dev libreadline-dev zlib1g-dev libncurses5-dev libffi-dev \
            libgdbm6 libgdbm-dev

      - name: Install ruby-build and Ruby 3.1.4
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          sudo ./ruby-build/install.sh
          mkdir -p "$HOME/.rubies"
          ruby-build 3.1.4 "$HOME/.rubies/3.1.4"

      - name: Set PATH and install Bundler
        run: |
          echo "$HOME/.rubies/3.1.4/bin" >> $GITHUB_PATH
          ruby -v
          gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test  # or rspec, etc.
